const fs = require("fs");
const fetch = require("node-fetch");
const { execSync } = require("child_process");

async function runAI() {
  const convo = fs.readFileSync("./memory/convo.md", "utf-8");

  const prompt = `
You are an AI software engineer.

Read the conversation and generate a project.

IMPORTANT:
Return ONLY valid JSON.

FORMAT:
{
  "files": [
    {
      "path": "file path",
      "content": "file content"
    }
  ]
}

CONVERSATION:
${convo.slice(0, 8000)}
`;

  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": "Bearer " + process.env.OPENROUTER_API_KEY,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: "openai/gpt-4o-mini",
      max_tokens: 2000,
      messages: [{ role: "user", content: prompt }]
    })
  });

  const data = await res.json();

  if (!data.choices) {
    console.log("ERROR:", data);
    return;
  }

  const text = data.choices[0].message.content;

  fs.writeFileSync("./memory/output.json", text);

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    console.log("JSON PARSE ERROR");
    return;
  }

  parsed.files.forEach(file => {
    const dir = file.path.split("/").slice(0, -1).join("/");
    if (dir) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(file.path, file.content);
  });

  console.log("Files generated by AI.");

  // 🔥 AUTO COMMIT + PUSH
  try {
    execSync("git config user.name 'AI Bot'");
    execSync("git config user.email 'ai@bot.com'");
    execSync("git add .");
    execSync("git commit -m '🤖 AI generated project update' || echo 'No changes'");
    execSync("git push");

    console.log("Changes pushed to GitHub.");
  } catch (err) {
    console.log("Git error:", err.message);
  }
}

runAI();
