name: Docker Push

on:
  workflow_run:
    workflows: ["Docker Build"]
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker image
        run: |
          echo "Pushing Docker image to DockerHub"