name: Release Notes

on:
  push:
    paths:
      - docs/CHANGELOG.md
      - docs/Task.md

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Notes
        run: |
          echo "Release Notes from CHANGELOG and Task files"