name: Tagging

on:
  push:
    paths:
      - docs/VERSION.md

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        run: |
          TAG=$(cat docs/VERSION.md | grep VERSION | awk '{print $2}')
          git tag -a "$TAG" -m "Release version $TAG"
          git push origin "$TAG"