name: Validator

on:
  workflow_run:
    workflows: ["Task Runner"]
    types: [completed]

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Changes
        run: |
          echo "Validating changes before merge"