name: Versioning

on:
  push:
    paths:
      - docs/VERSION.md

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Read VERSION.md
        id: version
        run: |
          VERSION=$(cat docs/VERSION.md | grep VERSION | cut -d ' ' -f 2)
          echo "::set-output name=version::$VERSION"
      - name: Auto-increment version
        run: |
          # Logic for version bump goes here.